// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: commod.proto

package base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//
type Txt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txt string `protobuf:"bytes,1,opt,name=txt,proto3" json:"txt,omitempty"`
}

func (x *Txt) Reset() {
	*x = Txt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commod_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Txt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Txt) ProtoMessage() {}

func (x *Txt) ProtoReflect() protoreflect.Message {
	mi := &file_commod_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Txt.ProtoReflect.Descriptor instead.
func (*Txt) Descriptor() ([]byte, []int) {
	return file_commod_proto_rawDescGZIP(), []int{0}
}

func (x *Txt) GetTxt() string {
	if x != nil {
		return x.Txt
	}
	return ""
}

var File_commod_proto protoreflect.FileDescriptor

var file_commod_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x62, 0x61, 0x73, 0x65, 0x22, 0x17, 0x0a, 0x03, 0x54, 0x78, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74,
	0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x78, 0x74, 0x42, 0x07, 0x5a,
	0x05, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_commod_proto_rawDescOnce sync.Once
	file_commod_proto_rawDescData = file_commod_proto_rawDesc
)

func file_commod_proto_rawDescGZIP() []byte {
	file_commod_proto_rawDescOnce.Do(func() {
		file_commod_proto_rawDescData = protoimpl.X.CompressGZIP(file_commod_proto_rawDescData)
	})
	return file_commod_proto_rawDescData
}

var file_commod_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_commod_proto_goTypes = []interface{}{
	(*Txt)(nil), // 0: base.Txt
}
var file_commod_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_commod_proto_init() }
func file_commod_proto_init() {
	if File_commod_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_commod_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Txt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_commod_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commod_proto_goTypes,
		DependencyIndexes: file_commod_proto_depIdxs,
		MessageInfos:      file_commod_proto_msgTypes,
	}.Build()
	File_commod_proto = out.File
	file_commod_proto_rawDesc = nil
	file_commod_proto_goTypes = nil
	file_commod_proto_depIdxs = nil
}
